// Action types
const ADD_NATIONALITY = 'ADD_NATIONALITY';
const REMOVE_NATIONALITY = 'REMOVE_NATIONALITY';

// Nationalities
const SWISS = 'CH';
const SPANISH = 'ES';
const BRITISH = 'BR';
const FRENCH = 'FR';
const NATIONALITIES = [SWISS, SPANISH, BRITISH, FRENCH];

export { NATIONALITIES, SWISS, SPANISH, BRITISH, FRENCH, ADD_NATIONALITY, REMOVE_NATIONALITY };
