// Action types
const ADD_FETCH_NATIONALITY_FILTER = 'ADD_FETCH_NATIONALITY_FILTER';
const REMOVE_FETCH_NATIONALITY_FILTER = 'REMOVE_FETCH_NATIONALITY_FILTER';
const FETCH_USERS_BEGIN = 'FETCH_USERS_BEGIN';
const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

// Fetch configuration
const PAGE_SIZE = 50;
const MAX_CATALOGUE_SIZE = 1000;

// Nationalities
const SWISS = 'CH';
const SPANISH = 'ES';
const BRITISH = 'BR';
const FRENCH = 'FR';
const NATIONALITIES = [SWISS, SPANISH, BRITISH, FRENCH];

export {
  PAGE_SIZE,
  MAX_CATALOGUE_SIZE,
  NATIONALITIES,
  SWISS,
  SPANISH,
  BRITISH,
  FRENCH,
  ADD_FETCH_NATIONALITY_FILTER,
  REMOVE_FETCH_NATIONALITY_FILTER,
  FETCH_USERS_BEGIN,
  FETCH_USERS_SUCCESS,
  FETCH_USERS_FAILURE,
};
